apiVersion: v1
kind: Template
labels:
  template: angular-springboot-example
metadata:
  annotations:
    description: Pipeline ANGULAR 
    iconClass: icon-jenkins
    tags: angular ,node,jenkins
  creationTimestamp: null
  name: angular-demo-pipeline
objects:
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: ${APP_NAME}-pipeline
    spec:
      strategy:
        jenkinsPipelineStrategy: 
          jenkinsfile: |-
            pipeline {

                agent {
                        node {
                            label "maven"
                        }
                        
                    }
                    
                tools {
                        jdk 'openjdk8'
                }  

                parameters {
                    string(name: 'PROJECT_NAME', defaultValue: 'fuse-demo-project', description: 'What is the project name?')
                    string(name: 'APP_NAME', defaultValue: 'fuse-soap-app', description: 'What is the application name?')
                }   

                environment
                {
                    def version = ""
                    def artifactId = ""
                    def rollout = true
                }

            

                stages {  
            
                    stage("Initilize") {
                        
                        steps {
                            script {
                                git branch: "master", credentialsId: "githubid", url: "https://github.com/iam-roger-io/fuse-soap.git" 
                            
                                version = readMavenPom().getVersion();
                                echo "Version ::: ${version}"

                                artifactId = readMavenPom().getArtifactId()
                                echo "artifactId ::: ${artifactId}"

                                echo " matcher :::::: ${env.BRANCH_NAME} "
                            
                            }
                        }
                    }     
            
                    stage("Build Project") {
                        steps {
                            script {
                                withMaven( maven: "M361", mavenSettingsConfig: "maven-settings") {
                                    sh  '''
                                    export JAVA_HOME=/usr/lib/jvm/java-1.8.0
                                
                                    echo JAVA_HOME=$JAVA_HOME
                                
                                
                                    mvn install -DskipTests=true
                                
                                    '''                    
                                }
                            }
                        }
                    }   

                    stage('Create Image Builder') {
                        steps {
                            script {
                                openshift.withCluster() {
                                    openshift.withProject("${params.PROJECT_NAME}") {
                                        echo "Using project: ${openshift.project()}"
                                        if (!openshift.selector("bc", "${artifactId}").exists()) {
                                            openshift.newBuild("--name=${artifactId}", "--docker-image=registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift:1.8", "--binary")                            
                                        }
                                    }
                                }
                            }
                        }
                    }

                    stage('Start Build Image') {
                        steps {
                            script {
                                openshift.withCluster() {
                                    openshift.withProject("${params.PROJECT_NAME}") {
                                        echo "Using project: ${openshift.project()}"
                                        openshift.selector("bc", "${artifactId}").startBuild("--from-file=target/${artifactId}-${version}.jar", "--wait=true")
                                    }
                                }
                            }
                        }
                    }


                    stage('Promote to DEV') {
                        steps {
                            script {
                                openshift.withCluster() {
                                    openshift.withProject("${params.PROJECT_NAME}") {
                                        openshift.tag("${artifactId}:latest", "${artifactId}:${version}")
                                    }   
                                }
                            }
                        }
                    }

                    stage('Create ServiceAccount') {
                        steps {
                            script {
                                openshift.withCluster() {
                                    openshift.withProject("${params.PROJECT_NAME}") {
                                        if (!openshift.selector('sa', "${artifactId}").exists()) {
                                            openshift.create('sa', "${artifactId}")
                                        }                            
                                        openshift.raw('policy', 'add-role-to-user', 'view', "system:serviceaccount:${params.PROJECT_NAME}:${artifactId}")
                                    }
                                }
                            }
                        }
                    }

                    stage('Create DEV') {
                        when {
                            expression {
                                openshift.withCluster() {
                                    openshift.withProject("${params.PROJECT_NAME}") {
                                        return !openshift.selector('dc', "${artifactId}").exists()
                                        
                                    }
                                }
                            }
                        }

                        steps {
                            script {
                                openshift.withCluster() {
                                    openshift.withProject("${params.PROJECT_NAME}") {
                                        if (!openshift.selector('dc', "${artifactId}").exists()) {
                                            openshift.newApp("registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift:latest~https://github.com/iam-roger-io/fuse-soap.git",
                                            " -p APP_NAME=${artifactId}",
                                            " -p APP_VERSION=${version}",
                                            " -p NAMESPACE=${params.PROJECT_NAME}",
                                            " -p CPU_REQUEST=0.2",
                                            " -p MEMORY_REQUEST=256Mi",
                                            " -p CPU_LIMIT=1.0",
                                            " -p MEMORY_LIMIT=256Mi")

                                            rollout = false
                                        }
                                    }
                                }
                            }
                        }
                    }


                    stage('Rollout Version Container') {
                        when {
                            expression {
                                return rollout
                            }
                        }

                        steps {
                            script {
                                openshift.withCluster() {
                                    openshift.withProject("${params.PROJECT_NAME}") {
                                        echo "Using project ::: ${openshift.project()}"
                                        // Getting the deploymentConfig
                                        def deploymentConfig = openshift.selector("dc", "${artifactId}").object()

                                        for(int a=0; a<deploymentConfig.spec.triggers.size(); a++ ) {
                                            if(deploymentConfig.spec.triggers[a].toString().contains("imageChangeParams")) {
                                                if("${deploymentConfig.spec.triggers[a].imageChangeParams.from.name}" != "${artifactId}:${version}") {
                                                    echo "ContainerImage changed to ::: ${deploymentConfig.spec.triggers[a].imageChangeParams.from.name}"
                                                    deploymentConfig.spec.triggers[a].imageChangeParams.from.name="${artifactId}:${version}"
                                                    openshift.apply(deploymentConfig)
                                                }
                                                else {
                                                    echo "Wasn't possible change the Image, because is the same to the previous."
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
          env:
          - name: PROJECT_NAME
            value: ${BASE_PROJECT_NAME}
          - name: APP_NAME
            value: ${APP_NAME}

parameters:
- description: The base project name
  displayName: Base project name
  name: BASE_PROJECT_NAME
  required: true
- description: The name assigned to the application.
  displayName: Application Name
  name: APP_NAME
  required: true

